# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digit_recognition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64igit_recognition.proto\x12\x10\x64igitrecognition\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\t\"M\n\x10PredictionResult\x12\x17\n\x0fpredicted_label\x18\x01 \x01(\t\x12 \n\x18probability_distribution\x18\x02 \x03(\x02\x32j\n\x17\x44igitRecognitionService\x12O\n\tSendImage\x12\x1e.digitrecognition.ImageRequest\x1a\".digitrecognition.PredictionResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digit_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=45
  _globals['_IMAGEREQUEST']._serialized_end=74
  _globals['_PREDICTIONRESULT']._serialized_start=76
  _globals['_PREDICTIONRESULT']._serialized_end=153
  _globals['_DIGITRECOGNITIONSERVICE']._serialized_start=155
  _globals['_DIGITRECOGNITIONSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
